[build]
  publish = "build"  # Make sure this matches your actual build output directory
  command = "npm install --legacy-peer-deps && npm run build"
  base = "/"  # This is usually the root directory, adjust if necessary

[context.production]
  branch = "chris"  # Ensure this branch exists and is the correct branch name
